apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-catalogue
  namespace: roboshop
  labels:
    project: roboshop
    component: catalogue
    environment: dev
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    component: catalogue
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels: 
       project: roboshop
       component: catalogue
       environment: dev
  template:
    metadata:
      labels:
        project: roboshop
        component: catalogue
        environment: dev
    spec:
      containers:
        - name: catalogue
          image: raviteja471/catalogue:1.0.0
          envFrom:
          - ConfigMapRef:
              name: configmap-catalogue

---
apiVersion: v1  
kind: Service
metadata: 
  name: catalogue-service 
  namespace: roboshop 
  labels:
       project: roboshop
       component: catalogue
       environment: dev
spec:
  selector:
     project: roboshop
     component: catalogue
     environment: dev

  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080